server:
  port: 8084

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://localhost:3306/fitness_db
    username: root
    password: Vik@s1572

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true